### ISSUE TITLE
Way to change namespace of generated class

### ISSUE THREAD

**Issue by Hau-Hau** [codecentric/net_automatic_interface#19]
Hello!

I believe it would be wonderful to have the ability to modify the namespace of the generated interfaces. For instance, this could be achieved through a parameter in attribute: [GenerateAutomaticInterface("New.Important.Namespace")] or at least through csproj configuration.

The reasoning behind implementing this feature is that we frequently desire to maintain abstractions in a distinct library, package, or namespace from the concrete implementation.

**Comment by ChristianSauer** [comment]
This is in 2.1.0
