### ISSUE TITLE
Will the repository be maintained?

### ISSUE THREAD

**Issue by awasilik** [codecentric/net_automatic_interface#22]
@ChristianSauer will the repository be maintained anyhow? 

I am not sure if I should invest time into preparing PR with fixes. I find this tool very useful, but it could use some improvements and one fix to be possible to be used.

Please leave a note. Thank you

**Comment by ChristianSauer** [comment]
Yes, I would love to!
My family and I where hit hard with corona so I behind on a lot of projects.
Hopefully this will change in the near future.

**Comment by awasilik** [comment]
Great to hear :) I saw one PR that was abandoned that fixed the issue 
https://github.com/codecentric/net_automatic_interface/issues/18

If I spend some time to revive it would you be willing to publish new updated nuget?

**Comment by ChristianSauer** [comment]
Thjat should be fixed in 2.0.0, if not can you create a ticket?

**Comment by awasilik** [comment]
Yes, thanks for the update!

The issue has been solved, but the new one preventing the usage occur :( 

Nevertheless, good job with changing to IncrementalGenerator, seems like a big step forward.

**Comment by ChristianSauer** [comment]
Did 2.1.0 fix the issues?

**Comment by awasilik** [comment]
Fixed the issue with two interfaces generated in the same namespace, but brought back the issue with invalid treating of default boolean parameters :(

The one with nullable types giving warnings is not fixed too.

**Comment by ChristianSauer** [comment]
@awasilik Can you please open a new issue with a sample (ideally 2.1.1). The relevant tests are still green so there must be a broken assumption
