### ISSUE TITLE
Can not generate interface for two classes in same directory

### ISSUE THREAD

**Issue by awasilik** [codecentric/net_automatic_interface#25]
Thanks for the update! After latest change to 2.0.0 AutomaticInterface can not generate interface for two classes in the same directory with same namespace.
Generation produced error:

CSC: Warning CS8785 : Generator 'AutomaticInterfaceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'ProjectName.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'.

**Comment by ChristianSauer** [comment]
I noticed this just this minute, too. I think 2.1.0 should fix this issue.
Rather annoying limitation of  the incremental generators, see https://github.com/dotnet/roslyn/discussions/60272
It should be fixed for most cases but could still cause problems if there are two files with the same name in the namespace.

**Comment by ChristianSauer** [comment]
Is this still an issue?
