### ISSUE TITLE
Nullable types in interface generate a compilation warning.

### ISSUE THREAD

**Issue by awasilik** [codecentric/net_automatic_interface#26]
When AutomaticInterface generates an interface for a class that has nullable types as parameter or return type the compilation warning is produced saying:

_Warning CS8669 : The annotation for nullable reference types should only be used in code within a '#nullable' annotations _context. Auto-generated code requires an explicit '#nullable' directive in source._

I think the newest version removed explicit "#nullable enable" directive

**Comment by ChristianSauer** [comment]
Can you give me a sample?
It does not cause this for me.
2.0.0 still generates the nullable directive, if there is at least one nullable type in the class.
That might be a bug in 2.0.0 where we do not pick up all nullable types, so a sample would be welcome

**Comment by awasilik** [comment]
Below there is a sample of code that produces the warning. It's a company project so I had to obfuscate it a bit.

class:
<img width="946" alt="image" src="https://github.com/codecentric/net_automatic_interface/assets/33750371/53b653a1-23b8-46ee-83a8-0498913911e2">

generated interface:
<img width="1275" alt="image" src="https://github.com/codecentric/net_automatic_interface/assets/33750371/b7d32c0d-1874-4111-bb5b-8054c5d34832">

class that is not treated as nullable:
<img width="801" alt="image" src="https://github.com/codecentric/net_automatic_interface/assets/33750371/997cc0d8-2f64-43e2-9f19-9f62af86f98a">


One thing worth to notice is that the MediumEvent class is in different project than

**Comment by ChristianSauer** [comment]
Feel free to reopen if it persis
