### ISSUE TITLE
out keyword in method parameter is missing in interface

### ISSUE THREAD

**Issue by konrad-gora** [codecentric/net_automatic_interface#38]
This is my class:
```
[GenerateAutomaticInterface]
public class SomeClass : ISomeClass
{
    public void SomeMethod(out int someOutParameter)
    {
        someOutParameter = 1;
    }
}
```
This is the generated interface:
```
[GeneratedCode("AutomaticInterface", "")]
public partial interface ISomeClass
{
    /// <inheritdoc />
    void SomeMethod(int someOutParameter);
    
}
```

The `out` keyword is missing in the interface. Because of that, I'm getting a compilation error:
CS0535	'SomeClass' does not implement interface member 'ISomeClass.SomeMethod(int)'

**Comment by mohummedibrahim** [comment]
@konrad-gora  Yes, I'm also having the same issue with `ref` and `in` too. Looks like the `out`, `ref`, and `in` are not implemented yet in the source generator. 

@ChristianSauer  A quick fix/implementation could be perhaps checking [RefKind](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.refkind?view=roslyn-dotnet-4.7.0) on `IParameterSymbol` in [Builder class](https://github.com/codecentric/net_automatic_interface/blob/master/AutomaticInterface/AutomaticInterface/Builder.cs#L177C26-L177C27).

**Comment by ChristianSauer** [comment]
Should be in 2.3.0

**Comment by konrad-gora** [comment]
I can just confirm that it is working now :)
