### ISSUE TITLE
Add support for `initial` keyword

### ISSUE THREAD

**Issue by WizzardMaker** [codecentric/net_automatic_interface#44]
I'm using the `initial` keyword in some of my properties to limit the setting of them.
This generator replaces `initial` with `set`, which is not the desired behaviour

Code:
```cs
public class X {
    public uint Id { get; init; }
}
```

Generated interface:
```cs
[GeneratedCode("AutomaticInterface", "")]
public partial interface IPlayer
{
    /// <inheritdoc />
    uint Id { get; set; }
}
```

**Comment by ChristianSauer** [comment]
Ok, can you give 4.1.0 a try?

**Comment by ChristianSauer** [comment]
Should be in 4.1.0
