### ISSUE TITLE
Generic / nongeneric overloads are not created (tested 3.0.1-4.1.0)

### ISSUE THREAD

**Issue by realbart** [codecentric/net_automatic_interface#56]
I'm missing interfaces
Example code:

```
[GenerateAutomaticInterface]
public class AcrService
{
    public Task<T> CallAsync<T>(Func<AcrApiClient, Task<T>> func) => throw new NotImplementedException();

    public Task CallAsync(Func<AcrApiClient, Task> func) => throw new NotImplementedException();
}
```

This yields an interface with only one method 

```
//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace MobiManagement.AcrClient
{
    [GeneratedCode("AutomaticInterface", "")]
    public partial interface IAcrService
    {
        /// <inheritdoc />
        System.Threading.Tasks.Task<T> CallAsync<T>(System.Func<MobiManagement.AcrClient.AcrApiClient, System.Threading.Tasks.Task<T>> func) ;
        
    }
}
```

**Comment by ChristianSauer** [comment]
Oops - I think the new code to remove shadowing (via new...) interferes here. Ok I will look into it

**Comment by simonmckenzie** [comment]
This was my mistake 🤦‍♀️ - I should have passed in `genericOptions` when creating the `SymbolDisplayFormat` used for deduplication - I can have a look at this if you're busy @ChristianSauer.

**Comment by ChristianSauer** [comment]
Yes, if you have time.
I would guess the same problem applies to properties and Events

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by simonmckenzie** [comment]
Done. Note that this does not affect properties and events, since they can't be overloaded.

**Comment by ChristianSauer** [comment]
Should be fixed

**Comment by simonmckenzie** [comment]
I've refreshed PR #58 - this is still an issue.

**Comment by simonmckenzie** [comment]
Hi @ChristianSauer ,

This has not been fixed - it will be fixed when #58 is merged.

**Comment by simonmckenzie-DEECA** [comment]
Hi @realbart,

The fix for this was deployed in yesterday's release.

**Comment by simonmckenzie** [comment]
Hi @realbart,

The fix for this was deployed in yesterday's release.

**Comment by realbart** [comment]
Wonderful!

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
